### ISSUE TITLE
Add Static content pages

### ISSUE THREAD

**Issue by DenisCarriere** [EOSTribe/EOSVotes-UI#8]
Handle integrating the content into the buttons? We were thinking some kind of modal or static page that keeps the user on the voting platform

https://docs.google.com/document/d/1D2i_RHeUer7F-HnmnOHNqK29ogChCmFYoQFzHYmvjpE/edit?usp=sharing

**Comment by chillsauce** [comment]
This has been identified as a showstopper for the beta launch of EOSvotes.io and assigned to @stevefloyd

**Comment by stevefloyd** [comment]
All of this is resolved with this commit...

https://github.com/EOSTribe/EOSVotes-UI/commit/d48dabdf3e9890e19d859389e03fdffc96fd5b7e
